pipeline {
    agent any
    environment {
        GIT_REPO = 'https://github.com/shubham1910200/Devops_Project.git'
        BRANCH = 'main' // or whichever branch you want to build
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    // Clone the repository
                    git url: "${GIT_REPO}", branch: "${BRANCH}"
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image from the repository
                    docker.build("flask-app:${env.BUILD_ID}")
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    // Run tests inside the container
                    docker.image("flask-app:${env.BUILD_ID}").inside {
                        sh 'pytest tests/'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Deploy the Docker container
                    sh 'docker run -d -p 5000:5000 flask-app:${env.BUILD_ID}'
                }
            }
        }
    }
}
