pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/shubham1910200/Devops_Project.git',branch:'main' , credentialsId: 'jenkins'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("soma1999/todo-app","Todo-app")
                }
            }
        }
        stage('Run Tests') {
            steps {
                dir('Todo-app') {
                       sh 'pip install flask'
                       sh 'python3 -m unittest discover -s tests'
                }
             
            }
        }
        stage('Deploy') {
            steps {
                script {
                    dockerImage.run('-d -p 5000:5000')  // Run in detached mode
                }
            }
        }
    }
    post {
        always {
            cleanWs()  // Clean workspace after pipeline execution
        }
    }
}
